/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Currency;
import Currency.Units.*;

/**
 *
 * @author Tripl
 */
public class CurrencyApp extends javax.swing.JFrame {

    /**
     * Creates new form CurrencyApp
     */
    String[] currencyType = {//Creates the String list for the two JComboBoxes 
        "USD",
        "EURO",
        "GBP",
        "JPY",
        "KRW",
        "AUD",
        "CAD",
        "CNY",
        "MXN"
    };
    
   
    
    
    public CurrencyApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        startingCurrency = new javax.swing.JLabel();
        convertCurrencyButton = new javax.swing.JButton();
        desiredCurrency = new javax.swing.JLabel();
        currentCurrency = new javax.swing.JComboBox<>();
        convertCurrency = new javax.swing.JComboBox<>();
        arrowLabel = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        displayPanelLabel = new javax.swing.JLabel();
        currentCurrencyInput = new javax.swing.JTextField();
        appTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));

        startingCurrency.setText("Select Your Currency");

        convertCurrencyButton.setText("Convert");
        convertCurrencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertCurrencyButtonActionPerformed(evt);
            }
        });

        desiredCurrency.setText("Desired Currency");

        currentCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(currencyType));
        currentCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentCurrencyActionPerformed(evt);
            }
        });

        convertCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(currencyType));
        convertCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertCurrencyActionPerformed(evt);
            }
        });

        arrowLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        arrowLabel.setText("→");

        displayPanel.setBackground(new java.awt.Color(204, 204, 204));
        displayPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(displayPanelLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPanelLabel)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        currentCurrencyInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentCurrencyInputActionPerformed(evt);
            }
        });

        appTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        appTitle.setText("Currency Converter");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(convertCurrencyButton))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(startingCurrency)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(currentCurrencyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(arrowLabel)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desiredCurrency)
                            .addComponent(convertCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(appTitle)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        mainPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {convertCurrencyButton, currentCurrency, desiredCurrency, startingCurrency});

        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(appTitle)
                .addGap(39, 39, 39)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startingCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desiredCurrency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrowLabel)
                    .addComponent(currentCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentCurrencyInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(convertCurrencyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void currentCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentCurrencyActionPerformed

    private void convertCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convertCurrencyActionPerformed

    private void convertCurrencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertCurrencyButtonActionPerformed
        String currentSelection = (String) currentCurrency.getSelectedItem();
        String convertSelection = (String) convertCurrency.getSelectedItem();

        //try except
        double userCurrencyInput = 0.00;

        try {
            userCurrencyInput = Double.parseDouble(currentCurrencyInput.getText().toString());
            int currentSelectionIndex = linearSearch(currentSelection);  //Obtain index of chosen user quantity
            
             //Create array of the Currency Objects in respective Order as they are listed in currencyType[]
            Currency currencyObjectArray[] = createObjectArray(userCurrencyInput); //Since the objectArray is sorted to match the JComboBox array, it will take the integer index value from currentSelectionIndex and use that to select the correct Currency Object 
           
            //Performs the convert method of the Currency Class. This is then printed out in the toString method in the displayPanelLabel
            currencyObjectArray[currentSelectionIndex].convert(convertSelection);

            displayPanelLabel.setText(currencyObjectArray[currentSelectionIndex].toString() + " " + convertSelection);
        } 
        catch (Exception e) {
            System.out.println("Error: Invalid Input");
            displayPanelLabel.setText("Please enter only digits, 0-9, no special characters or spaces!");
        }
        
    }//GEN-LAST:event_convertCurrencyButtonActionPerformed

    private void currentCurrencyInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentCurrencyInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentCurrencyInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyApp().setVisible(true);
            }
        });
    }

    public int linearSearch(String query) {
        for(int i = 0; i < currencyType.length; i++) {
            if (currencyType[i] == query) {
                return i;
            }
        }
        return -1;
    }
    
    public static Currency[] createObjectArray(double amt) {
        Currency[] objectList = {
            new USD(amt),
            new EURO(amt),
            new GBP(amt),
            new JPY(amt),
            new KRW(amt),
            new AUD(amt),
            new CAD(amt),
            new CNY(amt),
            new MXN(amt)
            
        };
        return objectList;
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appTitle;
    private javax.swing.JLabel arrowLabel;
    private javax.swing.JComboBox<String> convertCurrency;
    private javax.swing.JButton convertCurrencyButton;
    private javax.swing.JComboBox<String> currentCurrency;
    private javax.swing.JTextField currentCurrencyInput;
    private javax.swing.JLabel desiredCurrency;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel displayPanelLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel startingCurrency;
    // End of variables declaration//GEN-END:variables
    
}
